---
name: Update Release tag
on:
  workflow_dispatch:
    inputs:
      Ref:
        required: true
        description: branch to update to (use tags/<tag name> for tag)
        type: string
        default: '/heads/main'
jobs:
  Update_Tag:
    runs-on: "ubuntu-latest"
    steps:
      - name: Update Tag
        uses: actions/github-script@v6
        env:
          REF: ${{inputs.Ref}}
        with:
          script: |
            const r = github.git.getRef({
              owner: "godaddy-wordpress",
              repo: "mwcs-deploy-action",
              ref: process.env.REF,
            });
            github.git.createRef({
              owner: "godaddy-wordpress",
              repo; "mwcs-deploy-action",
              ref: "/refs/heads/v1",
              sha: r.object.sha,
            });
