---
name: Update Release tag
on:
  workflow_dispatch:
    inputs:
      Ref:
        required: true
        description: branch to update to (use tags/<tag name> for tag)
        type: string
        default: '/heads/main'
jobs:
  Update_Tag:
    runs-on: "ubuntu-latest"
    steps:
      - name: Update Tag
        uses: actions/github-script@v6
        env:
          REF: ${{inputs.Ref}}
        with:
          script: |
            const r = await github.rest.git.getRef({
              owner: "godaddy-wordpress",
              repo: "mwcs-deploy-action",
              ref: process.env.REF
            });
            await github.rest.git.updateRef({
              owner: "godaddy-wordpress",
              repo: "mwcs-deploy-action",
              ref: "refs/tags/v1",
              sha: r.data.object.sha
            });
